id: PEE346C10
initial_creation_type: ocr
source_metadata:
  volumes:
    a2399d77cb8148d7b0dbfbac004d45f3:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: བདེན་པ་གཉིས་རྣམ་པར་འབྱེད་པའི་དཀའ་འགྲེལ།
      total_pages: 1557
      volume_number: 62
