id: PEE346C10
initial_creation_type: ocr
source_metadata:
  volumes:
    f89ab5bc6de24bc59c7972bc966408b9:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: བདེན་པ་གཉིས་རྣམ་པར་འབྱེད་པའི་དཀའ་འགྲེལ།
      total_pages: 1557
      volume_number: 62
