id: D03A1C774
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:08:58+00:00'
last_modified: '2022-05-27T09:59:47.708783+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    0e05:
      image_group_id: I1PD95907
      title: བདེན་པ་གཉིས་རྣམ་པར་འབྱེད་པའི་དཀའ་འགྲེལ།
      total_pages: 1557
      order: 62
      base_file: 0e05.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
